/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package TemplateGUI;

import EntityClass.Tiket;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author USER
 */
public class TemplateHistories extends javax.swing.JPanel {

    /**
     * Creates new form TemplateHistories
     */
    public TemplateHistories() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tanggalLabel = new javax.swing.JLabel();
        KAIlogo = new javax.swing.JLabel();
        panelInfo = new javax.swing.JPanel();
        JamBerangkatLabel = new javax.swing.JLabel();
        JamKedatanganLabel = new javax.swing.JLabel();
        stasiunLabel = new javax.swing.JLabel();
        keretaLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListPenumpang = new javax.swing.JList<>();
        penumpangLabel = new javax.swing.JLabel();
        hargaLabel = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(529, 215));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tanggalLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tanggalLabel.setForeground(new java.awt.Color(255, 153, 0));
        tanggalLabel.setText("PEMESANAN  DD/BB/TTTT");

        panelInfo.setBackground(new java.awt.Color(69, 87, 179));
        panelInfo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        JamBerangkatLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        JamBerangkatLabel.setForeground(new java.awt.Color(255, 255, 255));
        JamBerangkatLabel.setText("Jam Keberangkatan : JJ:MM");

        JamKedatanganLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        JamKedatanganLabel.setForeground(new java.awt.Color(255, 255, 255));
        JamKedatanganLabel.setText("Jam Kedatangan : JJ:MM");

        stasiunLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        stasiunLabel.setForeground(new java.awt.Color(255, 255, 255));
        stasiunLabel.setText("Stasiun : Xxxxx - Xxxxx (Lokasi Tujuan)");

        keretaLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        keretaLabel.setForeground(new java.awt.Color(255, 255, 255));
        keretaLabel.setText("Kereta : xxxxxxx (Jenis)");

        ListPenumpang.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(ListPenumpang);

        penumpangLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        penumpangLabel.setForeground(new java.awt.Color(255, 255, 255));
        penumpangLabel.setText("Penumpang :");

        hargaLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        hargaLabel.setForeground(new java.awt.Color(255, 255, 255));
        hargaLabel.setText("Nominal : Rp. xxxxxxx ");

        javax.swing.GroupLayout panelInfoLayout = new javax.swing.GroupLayout(panelInfo);
        panelInfo.setLayout(panelInfoLayout);
        panelInfoLayout.setHorizontalGroup(
            panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JamBerangkatLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(JamKedatanganLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(keretaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(hargaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(stasiunLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(penumpangLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );
        panelInfoLayout.setVerticalGroup(
            panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoLayout.createSequentialGroup()
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInfoLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(JamBerangkatLabel))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInfoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(penumpangLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelInfoLayout.createSequentialGroup()
                        .addComponent(JamKedatanganLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(stasiunLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(keretaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(hargaLabel)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(tanggalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(KAIlogo, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tanggalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(KAIlogo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public void loadPenumpang(List<Tiket> tikets){
        ListPenumpang.removeAll();
        String[] nama = new String[tikets.size()];
        for (int i=0; i<tikets.size(); i++){
            nama[i] = tikets.get(i).getNama() + " - " + tikets.get(i).getNomorKursi();
        }
        ListPenumpang.setListData(nama);
    }
    
    public JLabel getJamBerangkatLabel() {
        return JamBerangkatLabel;
    }

    public JLabel getJamKedatanganLabel() {
        return JamKedatanganLabel;
    }

    public JLabel getKAIlogo() {
        return KAIlogo;
    }

    public JList<String> getListPenumpang() {
        return ListPenumpang;
    }

    public JLabel getHargaLabel() {
        return hargaLabel;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public JLabel getKeretaLabel() {
        return keretaLabel;
    }

    public JPanel getPanelInfo() {
        return panelInfo;
    }

    public JLabel getPenumpangLabel() {
        return penumpangLabel;
    }

    public JLabel getStasiunLabel() {
        return stasiunLabel;
    }

    public JLabel getTanggalLabel() {
        return tanggalLabel;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JamBerangkatLabel;
    private javax.swing.JLabel JamKedatanganLabel;
    private javax.swing.JLabel KAIlogo;
    private javax.swing.JList<String> ListPenumpang;
    private javax.swing.JLabel hargaLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel keretaLabel;
    private javax.swing.JPanel panelInfo;
    private javax.swing.JLabel penumpangLabel;
    private javax.swing.JLabel stasiunLabel;
    private javax.swing.JLabel tanggalLabel;
    // End of variables declaration//GEN-END:variables
}
