package TemplateGUI;

import javax.swing.JButton;
import javax.swing.JLabel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Umar
 */
public class TemplateJadwal extends javax.swing.JPanel {

    /**
     * Creates new form TemplateJadwal
     */
    public TemplateJadwal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        namaKereta = new javax.swing.JLabel();
        tipeKereta = new javax.swing.JLabel();
        StasiunAwal = new javax.swing.JLabel();
        jamPergi = new javax.swing.JLabel();
        StasiunAkhir = new javax.swing.JLabel();
        jamSampai = new javax.swing.JLabel();
        harga = new javax.swing.JLabel();
        btnPesan = new javax.swing.JButton();
        kursiTersedia = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(153, 204, 255));
        setForeground(new java.awt.Color(153, 204, 255));
        setMinimumSize(new java.awt.Dimension(362, 86));
        setPreferredSize(new java.awt.Dimension(362, 86));

        namaKereta.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        namaKereta.setText("Kereta (01)");

        tipeKereta.setText("Ekonomi (EK)");

        StasiunAwal.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 10)); // NOI18N
        StasiunAwal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        StasiunAwal.setText("MALANG");

        jamPergi.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        jamPergi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jamPergi.setText("08.00");

        StasiunAkhir.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 10)); // NOI18N
        StasiunAkhir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        StasiunAkhir.setText("SOLO");

        jamSampai.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        jamSampai.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jamSampai.setText("13.00");

        harga.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        harga.setText("Rp. 200.000,-");

        btnPesan.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        btnPesan.setText("PESAN");
        btnPesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesanActionPerformed(evt);
            }
        });

        kursiTersedia.setText("Kursi tersedia");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namaKereta)
                    .addComponent(tipeKereta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jamPergi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StasiunAwal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(StasiunAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jamSampai, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(kursiTersedia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPesan, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(harga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {StasiunAkhir, StasiunAwal, jamPergi, jamSampai});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(harga)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPesan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kursiTersedia)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(StasiunAkhir)
                            .addComponent(StasiunAwal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(namaKereta))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jamPergi)
                            .addComponent(jamSampai)
                            .addComponent(tipeKereta))))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {StasiunAkhir, StasiunAwal, jamPergi, jamSampai});

    }// </editor-fold>//GEN-END:initComponents

    private void btnPesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPesanActionPerformed

    public JButton getBtnPesan() {
        return btnPesan;
    }

    public JLabel getStasiunAkhir() {
        return StasiunAkhir;
    }

    public JLabel getJamSampai() {
        return jamSampai;
    }

    public JLabel getHarga() {
        return harga;
    }

    public JLabel getNamaKereta() {
        return namaKereta;
    }

    public JLabel getTipeKereta() {
        return tipeKereta;
    }

    public JLabel getStasiunAwal() {
        return StasiunAwal;
    }

    public JLabel getJamPergi() {
        return jamPergi;
    }

    public JLabel getKursiTersedia() {
        return kursiTersedia;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel StasiunAkhir;
    private javax.swing.JLabel StasiunAwal;
    private javax.swing.JButton btnPesan;
    private javax.swing.JLabel harga;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jamPergi;
    private javax.swing.JLabel jamSampai;
    private javax.swing.JLabel kursiTersedia;
    private javax.swing.JLabel namaKereta;
    private javax.swing.JLabel tipeKereta;
    // End of variables declaration//GEN-END:variables
}
