/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import ClassDAO.PemesananDAO;
import EntityClass.Pemesanan;
import EntityClass.Tiket;
import Session.Session;
import TemplateGUI.TemplateHistories;
import java.awt.Dimension;
import java.time.format.DateTimeFormatter;
import javax.swing.Box;

/**
 *
 * @author Umar
 */
public class HistoryFrame extends javax.swing.JFrame {
    private PemesananDAO dao = new PemesananDAO();
    /**
     * Creates new form HistoryFrame
     */
    public HistoryFrame() {
        initComponents();
        this.setLocationRelativeTo(this);
        loadPanelHistory();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new raven.scroll.win11.ScrollPaneWin11();
        model = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        model.setLayout(new javax.swing.BoxLayout(model, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(model);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PESAN KERETA INDONESIA");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/LOGOkAI(50).png"))); // NOI18N
        jLabel2.setText("logoKAI(50)");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel3.setText("Informasi Pemesanan Jadwal Tiket Kereta Api");

        backBtn.setBackground(new java.awt.Color(255, 153, 0));
        backBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setText("←");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(36, 36, 36)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)))
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        this.dispose();
        new Dashboard().setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed
    
    private void loadPanelHistory(){
        model.removeAll();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("HH:mm");
        for (Pemesanan p : dao.getPesanans()) {
            if (p.getUserPembeli().getName().equals(Session.getUser().getName())){
                TemplateHistories panel = new TemplateHistories(p);
                String[] tanggal = p.getTanggal().split("-");
                panel.getTanggalLabel().setText("PEMESANAN " + tanggal[2] + "/" + tanggal[1] + "/" + tanggal[0]);
                panel.getJamBerangkatLabel().setText("Jam Keberangkatan : " + p.getJadwal().getWaktuKeberangkatan().format(formatter));
                panel.getJamKedatanganLabel().setText("Jam Kedatangan : " + p.getJadwal().getWaktuKedatangan().format(formatter));
                panel.getStasiunLabel().setText("Stasiun : " + p.getJadwal().getStasiunAwal().getNama() + " - " + p.getJadwal().getStasiunAkhir().getNama()+ " ("+ p.getJadwal().getStasiunAkhir().getKota()+")");
                panel.getKeretaLabel().setText("Kereta : " + p.getJadwal().getKereta().getNama() + "(" + p.getJadwal().getKereta().getTipeKereta() + ")");
                int hargaTotal=0;
                for (Tiket t : p.getItemOrder()) {
                    hargaTotal += p.getJadwal().getHarga();
                }
                panel.getHargaLabel().setText("Nominal : Rp." + hargaTotal);
                panel.loadPenumpang(p.getItemOrder());
                model.add(panel);
                model.add(Box.createRigidArea(new Dimension(0, 10)));
            }
        }
        model.revalidate();
        model.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel model;
    // End of variables declaration//GEN-END:variables
}
